//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullUPdateLog
    {
        public int Logid { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string LicenseKey { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
