//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoDataProcessedCompany
    {
        public GeoDataProcessedCompany()
        {
            this.GeoDataProcessedCustomers = new HashSet<GeoDataProcessedCustomer>();
        }
    
        public int CompanyCode { get; set; }
        public bool EnableProcessing { get; set; }
        public bool IsProcessing { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastProcessed { get; set; }
        public string StatusMessage { get; set; }
    
        public virtual ICollection<GeoDataProcessedCustomer> GeoDataProcessedCustomers { get; set; }
    }
}
