//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLog
    {
        public int id { get; set; }
        public string OrderID { get; set; }
        public string DeliveryAddressID { get; set; }
        public string CustomerID { get; set; }
        public string EmployeeID { get; set; }
        public string OrderDate { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string HoldProForma { get; set; }
        public string HoldNewCust { get; set; }
        public string RequiredbyDate { get; set; }
        public string OrderTotal { get; set; }
        public string ScannerID { get; set; }
        public string OrdTime { get; set; }
        public string Processed { get; set; }
        public string Free_Text { get; set; }
        public string QuoteLayoutID { get; set; }
        public string Company { get; set; }
        public string DISCPER { get; set; }
        public string ORDTYPE { get; set; }
        public string ORDSOURCE { get; set; }
        public string CUSTDISC { get; set; }
        public string CURR { get; set; }
        public string OrderTotalGross { get; set; }
        public string EmailConfirm { get; set; }
        public string EmailAddress { get; set; }
        public string InvoiceDate { get; set; }
        public string StartDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Payment { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Note { get; set; }
        public string Payment_Amount { get; set; }
        public string Payment_Date { get; set; }
        public string NextCall_Date { get; set; }
        public string OrderRep { get; set; }
        public string Printed { get; set; }
        public string Emailrep { get; set; }
        public string Creditemail { get; set; }
        public string Typeref { get; set; }
        public string BatchNo { get; set; }
        public string IsSend { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
