//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubOrderLog
    {
        public int id { get; set; }
        public string OrderId { get; set; }
        public string Line_No { get; set; }
        public string Barcode { get; set; }
        public string ProductID { get; set; }
        public string DateSold { get; set; }
        public string Quantity { get; set; }
        public string BasePrice { get; set; }
        public string UnitPrice { get; set; }
        public string SalePrice { get; set; }
        public string LineTotal { get; set; }
        public string Disc { get; set; }
        public string RequiredDate { get; set; }
        public string ExpectedDate { get; set; }
        public string Company { get; set; }
        public string Linetext { get; set; }
        public string DeliveryAddressCode { get; set; }
        public string OrderLineType { get; set; }
        public string OrderLinePriceType { get; set; }
        public string Line_Inner { get; set; }
        public string Line_Outer { get; set; }
        public string Priceband { get; set; }
        public string BatchNo { get; set; }
        public string CreatedDate { get; set; }
        public string IsSend { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
