//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDevice
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string Model { get; set; }
        public string SystemName { get; set; }
        public string DeviceVersion { get; set; }
        public System.DateTime CreateOn { get; set; }
    }
}
