//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLicenseCompany
    {
        public int ID { get; set; }
        public Nullable<int> License_ID { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string Company_Name { get; set; }
        public Nullable<decimal> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
