//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLicense
    {
        public int LicenseId { get; set; }
        public int CompanyId { get; set; }
        public int VersionId { get; set; }
        public string KeyContact { get; set; }
        public string Status { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string BillinType { get; set; }
        public string LicenseKey { get; set; }
        public Nullable<int> NoOfLicense { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<decimal> LastModifiedBy { get; set; }
    }
}
