//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsavesuborder
    {
        public int id { get; set; }
        public string orderid { get; set; }
        public string PRC4 { get; set; }
        public string Company { get; set; }
        public string OrderLineType { get; set; }
        public string PRC5 { get; set; }
        public Nullable<int> IsAllowDisc { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Line_Inner { get; set; }
        public string PRC1 { get; set; }
        public string PriceBand { get; set; }
        public Nullable<decimal> Sales_Ord_Val_outst { get; set; }
        public Nullable<decimal> Tot_Ord_Qty { get; set; }
        public string Req_Delv_Date { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public string LineText { get; set; }
        public string DeliveryAddressCode { get; set; }
        public Nullable<int> line_No { get; set; }
        public string ExpectedDate { get; set; }
        public Nullable<int> packqty3 { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public string PRC2 { get; set; }
        public Nullable<int> packprice3 { get; set; }
        public string PRC6 { get; set; }
        public string currenttime { get; set; }
        public string OrderLinePriceType { get; set; }
        public Nullable<int> Outst_Ord_Qty { get; set; }
        public string PRC3 { get; set; }
        public Nullable<decimal> Price_Ordered { get; set; }
        public Nullable<decimal> cbm { get; set; }
        public Nullable<int> SampleQty { get; set; }
        public Nullable<int> vatTotal { get; set; }
        public string Line_Outer { get; set; }
        public string Order_Number { get; set; }
        public string Product_Code { get; set; }
        public string vatcode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
