//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    
    public partial class UserLog
    {
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<int> Layout_no { get; set; }
        public string Print_Format { get; set; }
        public int UserId { get; set; }
        public string Rep_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string UserAppVersion { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string AppVersion { get; set; }
        public string LicenseKey { get; set; }
        public bool IsActive { get; set; }
        public int CompanyId { get; set; }
    }
}
