//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityTracking
    {
        public int Id { get; set; }
        public string ActivityType { get; set; }
        public int CompanyCode { get; set; }
        public Nullable<int> RepId { get; set; }
        public string LoggedInUser { get; set; }
        public string ActivityDetail { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
